transfer files to server

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -1,28 +1,24 @@
-#!/usr/bin/env bas
-# checking for command line arguments
+#!/usr/bin/env bash
+#Bash script that transfers a file from our client to a server:
 
-if [ $# -lt 4 ]
-then
-        echo "0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-        exit 1
+# check if there are enough parameters
+if [ $# -lt 4 ]; then
+  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-# assigning paramentals to variables
+# set variables for the parameters
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key="$4"
 
-path_to_file=$1
-ip=$2
-username=$3
-path_to_shh_key=$4
+# transfer the file using scp
+scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/
 
-# disabbling strict host key checking
-
-scp -0 "StrictHostkeyChecking=no" -i "$past_to_ssh_key" "$path_to_file" "$username@$ip:~/"
-
-
-# checking if the transfer was successful
-if [ $? -eq 0 ]
-then
-	echo "FILE WAS TRANSFERED SUCCESSFULLY
+# check the exit code of scp
+if [ $? -eq 0 ]; then
+  echo "File transfer successful"
 else
-	echo "FILE TRANSFER FAILED"
+  echo "File transfer failed"
 fi
